In [6]:
# load and show an image with Pillow
from PIL import Image
from numpy import asarray
import numpy as np


In [4]:
# Open the image form working directory
image = Image.open("./resources/geetestObj1.png") #.convert('L')
# convert image to numpy array
data = asarray(image)
print(type(data))
# summarize shape
print(data.shape)

<class 'numpy.ndarray'>
(48, 48, 4)


In [31]:
na = np.array([[[1,2,1,-1], [3,4,1,-1]], [[5,6,1,-1], [7,8,1,-1]]])
# summarize shape
print(na.shape)
print(na)
a=na[:,:,0:3]
b=na[:,:,3]
print('a shape', a.shape)
print(a)

print('b shape', b.shape)
print(b)

c=a + b[:,:,None]
print('c:')
print(c)


(2, 2, 4)
[[[ 1  2  1 -1]
  [ 3  4  1 -1]]

 [[ 5  6  1 -1]
  [ 7  8  1 -1]]]
a shape (2, 2, 3)
[[[1 2 1]
  [3 4 1]]

 [[5 6 1]
  [7 8 1]]]
b shape (2, 2)
[[-1 -1]
 [-1 -1]]
c:
[[[0 1 0]
  [2 3 0]]

 [[4 5 0]
  [6 7 0]]]
